// Everything the site says lives here — edit this file to update the portfolio.

export const profile = {
  name: 'Atul Lilhare',
  first: 'Atul',
  role: 'SDE-2',
  // Typed out one after another in the hero.
  roles: [
    'SDE-2 at CUBE.',
    'MERN stack developer.',
    'React Native developer.',
    'Full-stack engineer.',
    'I build things that ship.',
  ],
  company: 'CUBE',
  companyUrl: 'https://cube.ms',
  years: 4,
  since: 2022,
  github: 'https://github.com/AT00L',
  githubHandle: 'AT00L',
  leetcode: 'https://leetcode.com/u/MaiAtulHoon/',
  leetcodeHandle: 'MaiAtulHoon',
  linkedin: 'https://www.linkedin.com/in/atul-lilhare-27478b149',
  email: '442atulilhare@gmail.com',
  timezone: 'Asia/Kolkata',
  tzLabel: 'IST',
}

// The scrolling ticker under the hero.
export const stack = [
  'React Native',
  'Expo',
  'EAS Build',
  'OTA Updates',
  'React Navigation',
  'Push Notifications',
  'Firebase Analytics',
  'Google Maps',
  'iOS & Android',
  'JavaScript',
  'TypeScript',
  'React',
  'Redux Toolkit',
  'MUI',
  'Tailwind CSS',
  'i18next',
  'HOOPS 3D Viewer',
  'ExcelJS',
  'Electron',
  'Vite',
  'HTML & CSS',
  'Node.js',
  'Express',
  'REST APIs',
  'MVC Architecture',
  'Microservices',
  'MongoDB',
  'PostgreSQL',
  'Redis',
  'Zod',
  'Joi',
  'JWT',
  'Bcrypt',
  'SSO',
  'AWS EC2',
  'AWS S3',
  'AWS IAM',
  'Docker',
  'GitLab CI/CD',
  'SonarQube',
  'Sentry',
  'PostHog',
  'Microsoft Clarity',
  'Git',
  'GitHub',
  'Postman',
  'Axios',
  'Vitest',
  'Cypress',
  'ESLint',
  'Prettier',
  'Claude Code',
  'Chrome Extensions',
]

export const about =
  'I’m a software developer who likes the whole stack — from the pixel a user taps to the query that answers it. For four years I’ve been shipping production software at CUBE. I build for the web with React and for phones with React Native, and in between I make my own tools: browser extensions, APIs, full-stack apps.'

export const stats = [
  { value: 4, suffix: '+', label: 'Years shipping production code' },
  { value: 6, suffix: '', label: 'Public repos on GitHub' },
  { value: 3, suffix: '', label: 'Platforms I build for — web, iOS, Android' },
]

export const experience = [
  {
    company: 'CUBE',
    url: 'https://cube.ms',
    role: 'SDE-2 · Software Developer',
    period: '2022 — Present',
    years: 4,
    current: true,
    points: [
      'Build and ship features across the frontend and backend of production products.',
      'Turn product requirements into clean, maintainable code that holds up at scale.',
      'Review code, fix the hard bugs, and keep the team’s codebase healthy.',
    ],
    stack: [
      {
        label: 'Mobile',
        items: [
          'React Native',
          'Expo',
          'EAS Build',
          'OTA Updates',
          'React Navigation',
          'Push Notifications',
          'Firebase Analytics',
          'Google Maps',
        ],
      },
      {
        label: 'Web & Desktop',
        items: [
          'React',
          'TypeScript',
          'Redux Toolkit',
          'MUI',
          'Tailwind CSS',
          'i18next',
          'HOOPS 3D Viewer',
          'ExcelJS',
          'Electron',
        ],
      },
      {
        label: 'Backend',
        items: [
          'Node.js',
          'Express',
          'REST APIs',
          'MVC Architecture',
          'Microservices',
          'MongoDB',
          'PostgreSQL',
          'Redis',
          'Zod',
          'Joi',
          'JWT',
          'Bcrypt',
          'SSO',
        ],
      },
      {
        label: 'Cloud & DevOps',
        items: [
          'AWS EC2',
          'AWS S3',
          'AWS IAM',
          'Docker',
          'GitLab CI/CD',
          'SonarQube',
          'Sentry',
          'PostHog',
          'Microsoft Clarity',
        ],
      },
      {
        label: 'Tools & Testing',
        items: [
          'Git',
          'GitHub',
          'Postman',
          'Axios',
          'Vitest',
          'Cypress',
          'ESLint',
          'Prettier',
          'Claude Code',
        ],
      },
    ],
  },
]

// The Skills section. `logo` is a Simple Icons slug, or one of the line icons in
// SkillIcon.jsx for things that have no brand mark.
export const skills = [
  {
    title: 'Mobile',
    icon: 'mobile',
    blurb: 'Cross-platform apps in React Native and Expo — one codebase, a native feel on iOS and Android.',
    items: [
      { name: 'React Native', logo: 'react' },
      { name: 'Expo', logo: 'expo' },
      { name: 'EAS Build', logo: 'expo' },
      { name: 'OTA Updates', logo: 'refresh' },
      { name: 'React Navigation', logo: 'route' },
      { name: 'Push Notifications', logo: 'bell' },
      { name: 'Firebase Analytics', logo: 'firebase' },
      { name: 'Google Maps', logo: 'googlemaps' },
    ],
  },
  {
    title: 'Web & Desktop',
    icon: 'web',
    blurb: 'Fast, accessible interfaces in React and TypeScript — in the browser and on the desktop.',
    items: [
      { name: 'JavaScript', logo: 'javascript' },
      { name: 'TypeScript', logo: 'typescript' },
      { name: 'React', logo: 'react' },
      { name: 'Redux Toolkit', logo: 'redux' },
      { name: 'MUI', logo: 'mui' },
      { name: 'Tailwind CSS', logo: 'tailwindcss' },
      { name: 'i18next', logo: 'i18next' },
      { name: 'HOOPS 3D Viewer', logo: 'cube' },
      { name: 'ExcelJS', logo: 'table' },
      { name: 'Electron', logo: 'electron' },
      { name: 'Vite', logo: 'vite' },
      { name: 'HTML & CSS', logo: 'html5' },
    ],
  },
  {
    title: 'Backend',
    icon: 'server',
    blurb: 'APIs and services in Node.js and Express, backed by MongoDB, PostgreSQL and Redis, with real auth.',
    items: [
      { name: 'Node.js', logo: 'nodedotjs' },
      { name: 'Express', logo: 'express' },
      { name: 'REST APIs', logo: 'api' },
      { name: 'MVC Architecture', logo: 'layers' },
      { name: 'Microservices', logo: 'nodes' },
      { name: 'MongoDB', logo: 'mongodb' },
      { name: 'PostgreSQL', logo: 'postgresql' },
      { name: 'Redis', logo: 'redis' },
      { name: 'Zod', logo: 'zod' },
      { name: 'Joi', logo: 'shield' },
      { name: 'JWT', logo: 'jsonwebtokens' },
      { name: 'Bcrypt', logo: 'lock' },
      { name: 'SSO', logo: 'key' },
    ],
  },
  {
    title: 'Cloud & DevOps',
    icon: 'cloud',
    blurb: 'Shipping, monitoring and keeping production healthy.',
    items: [
      { name: 'AWS EC2', logo: 'aws' },
      { name: 'AWS S3', logo: 'aws' },
      { name: 'AWS IAM', logo: 'aws' },
      { name: 'Docker', logo: 'docker' },
      { name: 'GitLab CI/CD', logo: 'gitlab' },
      { name: 'SonarQube', logo: 'sonarqubeserver' },
      { name: 'Sentry', logo: 'sentry' },
      { name: 'PostHog', logo: 'posthog' },
      { name: 'Microsoft Clarity', logo: 'chart' },
    ],
  },
  {
    title: 'Tools & Testing',
    icon: 'tool',
    blurb: 'The everyday kit — plus the extensions and AI that speed it up.',
    items: [
      { name: 'Git', logo: 'git' },
      { name: 'GitHub', logo: 'github' },
      { name: 'Postman', logo: 'postman' },
      { name: 'Axios', logo: 'axios' },
      { name: 'Vitest', logo: 'vitest' },
      { name: 'Cypress', logo: 'cypress' },
      { name: 'ESLint', logo: 'eslint' },
      { name: 'Prettier', logo: 'prettier' },
      { name: 'Chrome Extensions', logo: 'googlechrome' },
      { name: 'Claude Code', logo: 'claude' },
    ],
  },
]

// Shown at the end of any project card with `madeWithClaude: true`.
export const claudeCredit = {
  label: 'Made using Claude',
  note: 'Idea to existence with Claude',
}

export const projectFilters = ['All', 'Full-stack', 'Frontend', 'Backend', 'Extension']

export const projects = [
  {
    id: 'url-shortener',
    categories: ['Full-stack', 'Backend'],
    name: 'URL Shortener',
    kind: 'Full-stack App',
    blurb:
      'A link shortener with user accounts. Sign up, log in, and manage your own short links with live click counts. JWT sessions in httpOnly cookies and hashed passwords, deployed on Vercel.',
    tags: ['Node.js', 'Express 5', 'MongoDB', 'JWT', 'Vercel'],
    repo: 'https://github.com/AT00L/URLSHORTNER',
    live: 'https://url.atulcode.com',
    visual: 'shortener',
  },
  {
    id: 'yourlabtest',
    categories: ['Full-stack', 'Frontend'],
    name: 'YourLabTest',
    kind: 'Monorepo',
    blurb:
      'A lab-test catalog browsable by category, with an admin view. A React + MUI + Tailwind client and an Express 5 + MongoDB product API, wired together with npm workspaces.',
    tags: ['React', 'MUI', 'Tailwind', 'Express 5', 'MongoDB'],
    repo: 'https://github.com/AT00L/YourLabTest',
    visual: 'monorepo',
  },
  {
    id: 'portfolio',
    categories: ['Frontend'],
    name: 'This Portfolio',
    kind: 'Website',
    blurb:
      'The site you’re scrolling. React 19 and Vite, with Lenis smooth scrolling and Motion for scroll-linked animation — tuned to stay at 60fps.',
    tags: ['React 19', 'Vite', 'Motion', 'Lenis'],
    repo: 'https://github.com/AT00L/Portfolio',
    visual: 'portfolio',
    madeWithClaude: true,
  },
  {
    id: 'css-injector',
    categories: ['Extension'],
    name: 'Custom CSS Injector',
    kind: 'Chrome Extension',
    blurb:
      'Pick any element on any site, write CSS for it, and have it reapplied on every visit — even after the site renames its ids and classes. Ranked selectors plus an element fingerprint re-find the node; a DevTools sidebar pane gives exact control.',
    tags: ['Manifest V3', 'JavaScript', 'DevTools API', 'Zero dependencies'],
    repo: 'https://github.com/AT00L/DOM-Styler-Custom-CSS-Injector',
    live: 'https://chromewebstore.google.com/detail/custom-css-injector/aebiehgbcchamlofdpcmdlfohffohghn',
    liveLabel: 'Chrome Web Store',
    liveCursor: 'Install',
    // Users and rating are fetched live from the Chrome Web Store (see useStoreStats.js).
    storeId: 'aebiehgbcchamlofdpcmdlfohffohghn',
    visual: 'injector',
    madeWithClaude: true,
  },
]
